sudo: false

language: ruby

cache:
  - bundler

rvm:
  - 2.3.3

env:
  global:
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - gem install jekyll jemoji

script:
  - bundle exec jekyll build
