sudo: false

language: ruby

cache:
  - bundler

env:
  global:
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - bundle install

script:
  - bundle exec jekyll build
