sudo: false

language: ruby

cache:
  - bundler

rvm:
  - 2.3.3

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - bundle install

script:
  - bundle exec jekyll build

deploy:
  provider: s3
  access_key_id:
    secure: YICd1p6dt+Af16M7zzVusd/WfoeqSXVAsz9Xt0jOksKX3LBV3bTSXogITQ0KR2fzayta0diMATOY64jRw83gUGJvHqkwWqGFPmxWmIsdhIN4Yg+ByCjXFJeTKl3mAJO79T3mhLwcG5lIk7AhepKxltdFiYClTLPC0SCjIR+Jp9g=
  secret_access_key:
    secure: PbUBnAdUirknTDg+pd7WeOH9ezJs8x5jfb1DEkqpuP65ksCqEF2ra3M28Ne4J/2SdFdFbdWVC6uwvCEKh4E1VeBgLmlqc5F2kQvw01DujHypFj51JN56hJ4nkqN8mN2U0sLgfmpLBMkFAz58CtBl5KODz29lnhvkghqcJWIikQs=
  bucket: www.californiacivicdata.org
  region: us-west-2
  skip_cleanup: true
  local_dir: _site
  acl: public_read
  on:
    branch: master
